//TRATAMENTO DE PARÂMETROS DE FORMA DINÂMICA
//FUNÇÃO QUE NÃO RECEBE NENHUM PARÂMETRO
//VARIÁVEL AUXILIAR PARA EXIBIR A SOMA DE TODOS OS PARÂMETROS PASSADOS
//PARA CADA INDICE DENTRO DOS ARGUMENTOS(PARÂMETROS). A VARIÁVEL AUXILIAR IRÁ SOMAR O ELEMENTO CONTIDO EM CADA INDICE
//RETORNANDO O VALOR DA SOMA
function soma(){
  var result = 0
  for(let i in arguments ){
    result += arguments[i]
  }
  return result;
};
//CONFORME A ADIÇÃO DE PARÂMETROS, A SOMA OCORRERÁ NORMALMENTE. 
//CASO UMA STRING SEJA ADICIONADA, SERÁ CONCATENADA AO RESULTADO DA SOMA ANTERIOR.
console.log(soma(10, 20, 30, 10,));